use bevy::{
    asset::RenderAssetUsages,
    math::{Vec3, primitives::Primitive3d},
    mesh::{Indices, Mesh, MeshBuilder, Meshable, MeshVertexAttribute, PrimitiveTopology},
    render::render_resource::VertexFormat,
};

pub const ATTRIBUTE_TIME: MeshVertexAttribute = MeshVertexAttribute::new(
    "Vertex_Time",
    1092837, // arbitrary unique ID for custom attribute
    VertexFormat::Float32,
);

/// A trail mesh generated by interpolating between a previous line and a current line over time.
#[derive(Copy, Clone, Debug)]
pub struct Trail {
    pub prev_root: Vec3,
    pub prev_tip: Vec3,
    pub curr_root: Vec3,
    pub curr_tip: Vec3,
    pub prev_time: f32,
    pub curr_time: f32,
    pub resolution: u32,
}

impl Primitive3d for Trail {}

impl Trail {
    #[inline]
    pub fn new(
        prev_root: Vec3,
        prev_tip: Vec3,
        curr_root: Vec3,
        curr_tip: Vec3,
        prev_time: f32,
        curr_time: f32,
    ) -> Self {
        Self {
            prev_root,
            prev_tip,
            curr_root,
            curr_tip,
            prev_time,
            curr_time,
            resolution: 32,
        }
    }

    pub fn with_resolution(mut self, resolution: u32) -> Self {
        assert!(resolution > 0, "resolution must be greater than 0");
        self.resolution = resolution;
        self
    }
}

impl Meshable for Trail {
    type Output = TrailMeshBuilder;

    fn mesh(&self) -> Self::Output {
        TrailMeshBuilder {
            prev_root: self.prev_root,
            prev_tip: self.prev_tip,
            curr_root: self.curr_root,
            curr_tip: self.curr_tip,
            prev_time: self.prev_time,
            curr_time: self.curr_time,
            resolution: self.resolution,
        }
    }
}

pub struct TrailMeshBuilder {
    pub prev_root: Vec3,
    pub prev_tip: Vec3,
    pub curr_root: Vec3,
    pub curr_tip: Vec3,
    pub prev_time: f32,
    pub curr_time: f32,
    pub resolution: u32,
}

impl MeshBuilder for TrailMeshBuilder {
    fn build(&self) -> Mesh {
        let mut vertices = Vec::new();
        let mut normals = Vec::new();
        let mut uvs = Vec::new();
        let mut times = Vec::new();
        let mut indices = Vec::new();

        let resolution_f = self.resolution as f32;

        for i in 0..=self.resolution {
            let t = i as f32 / resolution_f;

            // Interpolate root and tip using slerp.
            let root = self.prev_root.slerp(self.curr_root, t);
            let tip = self.prev_tip.slerp(self.curr_tip, t);

            // Interpolate time linearly
            let time = self.prev_time + t * (self.curr_time - self.prev_time);

            // Calculate directions for normal computation
            let dir = (tip - root).normalize_or_zero();

            // Movement direction:
            let move_dir = if t < 0.99 {
                let next_root = self.prev_root.slerp(self.curr_root, t + 0.01);
                (next_root - root).normalize_or_zero()
            } else {
                let prev_root = self.prev_root.slerp(self.curr_root, t - 0.01);
                (root - prev_root).normalize_or_zero()
            };

            // Normal is the cross product of the movement direction and the line direction.
            let normal = move_dir.cross(dir).normalize_or_zero();

            // We generate two vertices: one at root, one at tip
            vertices.push(root);
            vertices.push(tip);

            // Both vertices at this slice have the same normal (perpendicular to the ribbon surface)
            normals.push(normal);
            normals.push(normal);

            // UVs: U goes from 0 to 1 across steps, V goes from 0 to 1 (root is 0.0, tip is 1.0)
            uvs.push([t, 0.0]);
            uvs.push([t, 1.0]);

            // Both vertices get the interpolated time
            times.push(time);
            times.push(time);
        }

        // Generate indices for a triangle strip (represented as a TriangleList for simplicity)
        for i in 0..self.resolution {
            let base = i * 2;
            let next = (i + 1) * 2;

            // Face 1: base (root), next (root), base + 1 (tip)
            indices.push(base);
            indices.push(next);
            indices.push(base + 1);

            // Face 2: base + 1 (tip), next (root), next + 1 (tip)
            indices.push(base + 1);
            indices.push(next);
            indices.push(next + 1);
        }

        // We make it double-sided to be visible from any angle.
        let vertex_count = vertices.len();
        let index_offset = vertex_count as u32;

        let mut other_vertices = vertices.clone();
        let other_uvs = uvs.clone();
        let mut other_normals = Vec::with_capacity(vertex_count);
        let other_times = times.clone();

        for n in &normals {
            other_normals.push(-*n);
        }

        vertices.append(&mut other_vertices);
        uvs.extend(other_uvs);
        normals.append(&mut other_normals);
        times.extend(other_times);

        // Indices for the second side (Inner) with reversed winding
        for i in 0..self.resolution {
            let base = i * 2 + index_offset;
            let next = (i + 1) * 2 + index_offset;

            indices.push(base);
            indices.push(base + 1);
            indices.push(next);

            indices.push(base + 1);
            indices.push(next + 1);
            indices.push(next);
        }

        Mesh::new(
            PrimitiveTopology::TriangleList,
            RenderAssetUsages::default(),
        )
        .with_inserted_indices(Indices::U32(indices))
        .with_inserted_attribute(Mesh::ATTRIBUTE_POSITION, vertices)
        .with_inserted_attribute(Mesh::ATTRIBUTE_NORMAL, normals)
        .with_inserted_attribute(Mesh::ATTRIBUTE_UV_0, uvs)
        .with_inserted_attribute(ATTRIBUTE_TIME, times)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_trail_mesh() {
        let trail = Trail::new(
            Vec3::new(1.0, 0.0, 0.0),
            Vec3::new(1.0, 1.0, 0.0),
            Vec3::new(0.0, 1.0, 0.0),
            Vec3::new(0.0, 2.0, 0.0),
            0.0,
            1.0,
        ).with_resolution(10);
        
        let mesh = trail.mesh().build();
        
        // Resolution 10 means 11 steps.
        // Each step has 2 vertices.
        // Total vertices per side: 11 * 2 = 22.
        // Double-sided: 22 * 2 = 44.
        assert_eq!(mesh.count_vertices(), 44);
        
        // 10 segments.
        // Each segment has 2 triangles per side.
        // Each triangle has 3 indices.
        // Indices per side: 10 * 2 * 3 = 60.
        // Double-sided: 60 * 2 = 120.
        assert_eq!(mesh.indices().unwrap().len(), 120);

        // Verify that custom time attribute exists
        assert!(mesh.attribute(ATTRIBUTE_TIME.id).is_some());
    }
}
